spring.application.name=cdr-process-service

spring.main.web-application-type=none

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cdr_system}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=cdr-process-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

cdr.kafka.topic=${CDR_RAW_TOPIC:cdr-raw-topic}
cdr.kafka.dlt-topic=${CDR_DLT_TOPIC:cdr-raw-topic-dlt}
logging.level.com.example.cdrprocess=INFO
